// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./components/index/banner/index.vue')['default']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    HeadNav: typeof import('./components/headNav/index.vue')['default']
    PageHeader: typeof import('./components/headNav/pageHeader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
