// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./components/index/banner/index.vue')['default']
    Container: typeof import('./components/index/container/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    HeadNav: typeof import('./components/headNav/index.vue')['default']
    InfoDetail: typeof import('./components/common/infoDetail/index.vue')['default']
    PageHeader: typeof import('./components/headNav/pageHeader/index.vue')['default']
    Person: typeof import('./components/person/person.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Students: typeof import('./components/person/person.vue')['default']
    Tab: typeof import('./components/common/tab/index.vue')['default']
    Teachers: typeof import('./components/person/teachers.vue')['default']
  }
}
