// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./components/index/banner/index.vue')['default']
    Container: typeof import('./components/index/container/index.vue')['default']
    Editor: typeof import('./components/common/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Email: typeof import('./components/common/Email/index.vue')['default']
    ExamClass: typeof import('./components/admin/exam/examClass.vue')['default']
    FirstExam: typeof import('./components/admin/exam/firstExam.vue')['default']
    HeadNav: typeof import('./components/headNav/index.vue')['default']
    Index: typeof import('./components/admin/index/index.vue')['default']
    InfoDetail: typeof import('./components/common/infoDetail/index.vue')['default']
    PageHeader: typeof import('./components/headNav/pageHeader/index.vue')['default']
    Person: typeof import('./components/person/person.vue')['default']
    PrepareExam: typeof import('./components/admin/exam/prepareExam.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondExam: typeof import('./components/admin/exam/secondExam.vue')['default']
    SideNav: typeof import('./components/common/sideNav/index.vue')['default']
    Tab: typeof import('./components/common/tab/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
